(require 'fringe-helper)
(when nil
(set-fringe-mode 2)
(setq default-left-fringe-width 3)
(setq default-right-fringe-width 3)
(set-fringe-mode '(0 . 1))
;;(set-fringe-mode nil)
;;(set-fringe-mode '(0 . 0))
)
(require 'git-gutter+)
(defun git-changed () (interactive)
       (git-gutter+-show-staged-changes (buffer-file-name) default-directory))
(global-git-gutter+-mode t)
;;(setq left-fringe-width 0)
;;(set-window-fringes nil 4 5 nil)
(defun git-gutter+-remote-default-directory (dir file)
  (let* ((vec (tramp-dissect-file-name file))
          (method (tramp-file-name-method vec))
          (user (tramp-file-name-user vec))
          (domain (tramp-file-name-domain vec))
          (host (tramp-file-name-host vec))
          (port (tramp-file-name-port vec)))
     (tramp-make-tramp-file-name method user domain host port dir)))

(defun git-gutter+-remote-file-path (dir file)
  (let ((file (tramp-file-name-localname (tramp-dissect-file-name file))))
    (replace-regexp-in-string (concat "\\`" dir) "" file)))
(provide 'setup-git-gutter)
