(require 'hooks-defuns)
(provide 'setup-change-log)
(defun cleanup-change-log ()
  (widen)
  (beginning-of-buffer)
  (replace-string "../r" "racerx"))
(defun setup-change-log-hook ()
  (make-local-hook 'before-save-hook)
  (install-hook 'before-save-hook 'cleanup-change-log))
(install-hook 'change-log-mode-hook 'setup-change-log-hook)
