(require 'fringe-helper)
(set-fringe-mode 2)
(setq default-left-fringe-width 3)
(setq default-right-fringe-width 3)
(require 'git-gutter+)
(defun git-changed () (interactive)
       (git-gutter+-show-staged-changes (buffer-file-name) default-directory))
(global-git-gutter+-mode t)
;;(setq left-fringe-width 0)
;;(set-window-fringes nil 4 5 nil)
(set-fringe-mode '(0 . 1))
(provide 'setup-git-gutter)
